tasks:
  - name: Config Git
    command: rm -rf ~/.gitconfig && git clone https://gist.github.com/8963dd086da31cd752d4696b8600999d.git gitconfig_test_folder && cp -r ./gitconfig_test_folder/.gitconfig ~/ && rm -rf gitconfig_test_folder && exit

  - name: Adding global dependencies
    command: npm i -g expo-cli nodemon ts-node @expo/ngrok@^4.1.0 && exit

  - name: App terminal
    command: cd app
    openMode: split-left

  - name: Backend terminal
    command: cd backend
    openMode: split-right


vscode:
  extensions:
    - dracula-theme.theme-dracula
    - PKief.material-icon-theme
    - naumovs.color-highlight

ports:
  - port: 8081
    onOpen: notify
    visibility: public

  - port: 19000
    onOpen: notify
    visibility: public

  - port: 4040
    onOpen: notify
    visibility: public

  - port: 5037
    onOpen: notify
    visibility: public