tasks:
  - name: "Config Git"
    command: rm -rf ~/.gitconfig && git clone https://gist.github.com/8963dd086da31cd752d4696b8600999d.git gitconfig_test_folder && cp -r ./gitconfig_test_folder/.gitconfig ~/ && rm -rf gitconfig_test_folder && exit

  - name: "Adding global dependencies"
    command: "sudo npm i -g expo-cli nodemon @expo/ngrok@^4.1.0 && exit"

  - name: "App terminal"
    command: "cd app"
    openMode: "split-left"

  - name: "Backend terminal"
    command: "cd backend"
    openMode: "split-right"


vscode:
  extensions:
    - dracula-theme.theme-dracula
    - PKief.material-icon-theme
    - naumovs.color-highlight

ports:
  - port: 3000
    onOpen: ignore
    visibility: public

  - port: 8081
    onOpen: open-preview
    visibility: public

  - port: 19000
    onOpen: notify
    visibility: public